# Generated by Django 4.2 on 2023-04-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piscicultores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piscicultor', models.CharField(max_length=30)),
                ('rg', models.CharField(max_length=6)),
                ('contato', models.CharField(max_length=13)),
            ],
        ),
    ]
