# Generated by Django 4.2 on 2023-07-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peixes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=30)),
                ('pesoMedioPeixe_kg', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Racao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidaderacaokg', models.CharField(max_length=30)),
                ('marcaracao', models.CharField(max_length=30)),
                ('precoracao', models.CharField(max_length=30)),
                ('protreinabruta', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Viveiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biomassaViveiro', models.CharField(max_length=30)),
                ('dataIniciar', models.CharField(max_length=30)),
                ('mortalidade', models.CharField(max_length=30)),
                ('dataRetirada', models.CharField(max_length=30)),
                ('numeroViveiro', models.IntegerField()),
                ('temperatura', models.CharField(max_length=30)),
                ('largura_M', models.CharField(max_length=30)),
                ('ganhoViveiro', models.CharField(max_length=30)),
                ('ladoMenor_M', models.CharField(max_length=30)),
                ('pH_daAgua', models.CharField(max_length=30)),
                ('amostragemViveiro', models.CharField(max_length=30)),
                ('numeroPeixesViveiro', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='piscicultores',
            name='rg',
            field=models.CharField(max_length=7),
        ),
    ]
