# Generated by Django 4.2 on 2023-09-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piscicultores',
            old_name='piscicultor',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='piscicultores',
            name='contato',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='piscicultores',
            name='rg',
            field=models.CharField(max_length=20),
        ),
    ]
